node {

    checkout scm

    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
       /* def dockerfile = 'express-server/Dockerfile'*/
        def customImage = docker.build("dhikrahouissa/node-web-app")

        /* Push the container to the custom Registry */
        customImage.push()
    }
}
